### PR TITLE
Change the way access can be permanently granted for mobile users to …

### PR DESCRIPTION
**Pull request by bethylamine**
…remove webNavigation permissions

For issue #119 

@INSANEMODE can you test that this works as intended? There is a button on the options page that, when clicked, will request the needed permissions.

### CODE REVIEW

**Comment by INSANEMODE** [comment]
Button seems to work as intended on Firefox for Android, and doesn't do anything when pressed when the permissions have previously been granted. 

This is how it looks on my end. 
image

Seems good enough for the moment to prevent users from having to grant a new permission.
Do you want to keep the button like this, or have it only exist when needed? (when on mobile/when the host permissions aren't granted?)

**Comment by bethylamine** [comment]
only when needed ideally

**Comment by INSANEMODE** [comment]
Ok we can do this pretty easily.
I don't have write access to change anything in this pull request, and i can't suggest changes to code that hasn't been modifed in a code review, so i guess i'll just make the changes on my own branch to show what i am thinking.
you can see my changes here:
67e1e95982b0d97a57cb73170251ec8361bf212b

**Comment by bethylamine** [comment]
Look good. approved and merged.

**Pull request merged**
